resources:
- deployment.yaml
- webhook-configuration.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: webhook
  newName: dippynark/access-request-webhook
  newTag: latest
