---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: system
      path: /mutate
  failurePolicy: Fail
  name: webhook.accessrequests.iam.dippynark.co.uk
  rules:
  - apiGroups:
    - iam.dippynark.co.uk
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accessrequests
  sideEffects: None
# ---
# apiVersion: admissionregistration.k8s.io/v1
# kind: ValidatingWebhookConfiguration
# metadata:
#   creationTimestamp: null
#   name: validating-webhook-configuration
# webhooks:
# - admissionReviewVersions:
#   - v1beta1
#   clientConfig:
#     service:
#       name: webhook-service
#       namespace: system
#       path: /validate-iam-dippynark-co-uk-v1alpha1-accessrequest
#   failurePolicy: Fail
#   name: vaccessrequest.kb.io
#   rules:
#   - apiGroups:
#     - iam.dippynark.co.uk
#     apiVersions:
#     - v1alpha1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - accessrequests
#   sideEffects: None
