---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: system
      path: /mutate
  failurePolicy: Fail
  name: webhook.accessrequests.iam.dippynark.co.uk
  rules:
  - apiGroups:
    - iam.dippynark.co.uk
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accessrequests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: system
      path: /validate
  failurePolicy: Fail
  name: webhook.accessrequests.iam.dippynark.co.uk
  rules:
  - apiGroups:
    - iam.dippynark.co.uk
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accessrequests
  sideEffects: None
